name: CD - Hello World (Dev)

on:
  push:
    branches:
      - develop

jobs:
  cd-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello from CD
        run: echo "ðŸš€ Hello World from CD Pipeline (DEV)"

